/**
 * API module barrel export
 *
 * This file provides a single entry point for all API-related utilities,
 * error handling, and types.
 */

export * from './api-error-handler'
export type {
	ApiResponse,
	ApiError as ApiErrorType,
	PaginatedResponse,
	LoginRequest,
	LoginResponse,
	ResetPasswordRequest,
	UpdatePasswordRequest,
	CreateCheckoutRequest,
	CheckoutSession,
	VerifyPaymentRequest,
	VerifyPaymentResponse,
	BillingHistory,
	LetterDraft,
	GenerateLetterRequest,
	GenerateLetterResponse,
	LetterSubmitRequest,
	LetterReviewAction,
	LetterImproveRequest,
	LetterPdfRequest,
	SendEmailRequest,
	AdminLettersFilters,
	AdminLetterUpdateRequest,
	BatchLetterUpdateRequest,
	CreateCouponRequest,
	CouponStats,
	AdminAnalytics,
	EmployeeReferralLink,
	EmployeePayoutStats,
	RequestPayoutRequest,
	AcceptPrivacyPolicyRequest,
	ExportDataRequest,
	ExportDataResponse,
	DeleteAccountRequest,
	HealthCheckResponse,
	HealthCheck,
	RateLimitInfo,
	RateLimitResponse,
	EmailQueueItem,
	EmailQueueStats,
	CsrfTokenResponse,
} from './types'
