-- Migration: Add N8N workflow columns to letters table
-- Purpose: Align Supabase schema with N8N workflow output structure
-- Date: 2026-02-14
-- Related: N8N workflow ID fRWD4L9r7WH4m81HlAkhV

-- Add columns required by N8N workflow for jurisdiction research and letter drafting
ALTER TABLE letters
ADD COLUMN IF NOT EXISTS subject TEXT,
ADD COLUMN IF NOT EXISTS statutes_cited JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS legal_basis TEXT,
ADD COLUMN IF NOT EXISTS next_steps TEXT,
ADD COLUMN IF NOT EXISTS delivery_instructions TEXT;

-- Add indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_letters_subject ON letters(subject);
CREATE INDEX IF NOT EXISTS idx_letters_statutes_cited ON letters USING GIN(statutes_cited);

-- Add comments for documentation
COMMENT ON COLUMN letters.subject IS 'Letter subject line generated by AI (from N8N workflow)';
COMMENT ON COLUMN letters.statutes_cited IS 'Array of statutes cited in the letter (from jurisdiction research via Perplexity/SerpAPI)';
COMMENT ON COLUMN letters.legal_basis IS 'Summary of legal basis for the letter (from jurisdiction research)';
COMMENT ON COLUMN letters.next_steps IS 'Recommended next steps or actions for the client';
COMMENT ON COLUMN letters.delivery_instructions IS 'How the letter should be delivered based on jurisdiction requirements';
